# permissions for end users to view infrastructures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: infrastructure-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: curly-parakeet-example
    app.kubernetes.io/part-of: curly-parakeet-example
    app.kubernetes.io/managed-by: kustomize
  name: infrastructure-viewer-role
rules:
- apiGroups:
  - tbd.github.com
  resources:
  - infrastructures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tbd.github.com
  resources:
  - infrastructures/status
  verbs:
  - get
