# permissions for end users to view products.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: product-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: curly-parakeet-example
    app.kubernetes.io/part-of: curly-parakeet-example
    app.kubernetes.io/managed-by: kustomize
  name: product-viewer-role
rules:
- apiGroups:
  - tbd.github.com
  resources:
  - products
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tbd.github.com
  resources:
  - products/status
  verbs:
  - get
