apiVersion: tbd.github.com/v1
kind: Product
metadata:
  labels:
    app.kubernetes.io/name: product
    app.kubernetes.io/instance: product-sample
    app.kubernetes.io/part-of: curly-parakeet-example
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: curly-parakeet-example
  name: product-sample
spec:
